### ISSUE TITLE
Yocto implementation for Raspberry Pi

### ISSUE THREAD

**Issue by KhyatiSatta** [KhyatiSatta/final-project-KhyatiSatta#5]
DoD:

- [x] Successful yocto build for Raspberry PI.
- [x] Flash the image on an SD card
- [x] Ensure the Raspberry Pi boots up with the new custom image
- [x] Add wifi/ ethernet connection to the image.
- [x] Test internet connection using ping.
- [x] SSH into Raspberry PI for remote control.

Blockers:

No blockers.

**Comment by MaanasMDK** [comment]
Successfully was able to build, flash and boot up a minimal image using yocto for RaspberryPi 3b+. The image below shows the boot and login of root user on the custom image on the hardware.

Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/ffad39979c9297d7b1707322c3b392bdf78525ce

![Image](https://user-images.githubusercontent.com/89494511/231844534-ca93742e-dd3a-47d7-a41a-ea387ae1e504.jpeg)

**Comment by MaanasMDK** [comment]
Successfully able to add wifi/ethernet capabilities to Raspberry PI. 
Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/45d70ad1846e0147c548cf8b11e6e59b0f89ca22

Image below shows the IP configured on RaspberryPI and the successful ping to www.google.com


![Image](https://user-images.githubusercontent.com/89494511/232272464-cd832096-6fc2-4403-bbf6-e4bb38d5a8dc.jpeg)

**Comment by MaanasMDK** [comment]
Successfully was able to SSH into Raspberry PI using PowerShell on a Windows PC. The image below shows the IP address of Raspberry PI to prove it's the same system which was shown in the previous update comment.

![Image](https://user-images.githubusercontent.com/89494511/232272571-d68687ea-de6d-493c-a719-d3b92e4e00eb.png)

Updated Yocto to build from layers included as git submodules instead of local repositories in poky.
Commit Link : https://github.com/cu-ecen-aeld/final-project-MaanasMDK/commit/3ca69fb7c8a921c4e300b177b9160fe8db5eeb4e
